
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 24 23:43:45 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 3;
  public static final int CONST = 25;
  public static final int NUMCONST = 33;
  public static final int SEMI = 24;
  public static final int KEYWORD_EXTENDS = 48;
  public static final int KEYWORD_NEW = 46;
  public static final int MINUS = 13;
  public static final int KEYWORD_ELSE = 37;
  public static final int GRE = 10;
  public static final int OROR = 5;
  public static final int KEYWORD_CONTINUE = 41;
  public static final int KEYWORD_CLASS = 47;
  public static final int KEYWORD_READ = 43;
  public static final int KEYWORD_GOTO = 45;
  public static final int RECORD = 30;
  public static final int LS = 11;
  public static final int COMMA = 26;
  public static final int KEYWORD_DO = 38;
  public static final int LSE = 12;
  public static final int KEYWORD_RETURN = 42;
  public static final int DIV = 16;
  public static final int ANDAND = 6;
  public static final int PLUS = 14;
  public static final int LSQRB = 18;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 4;
  public static final int error = 1;
  public static final int KEYWORD_BREAK = 40;
  public static final int MUL = 15;
  public static final int LCURLY = 22;
  public static final int EQEQ = 7;
  public static final int MOD = 17;
  public static final int IDENT = 32;
  public static final int VOID = 27;
  public static final int EQ = 2;
  public static final int LBRACK = 20;
  public static final int RCURLY = 23;
  public static final int COLON = 28;
  public static final int KEYWORD_WHILE = 39;
  public static final int RBRACK = 21;
  public static final int CHARCONST = 34;
  public static final int RSQRB = 19;
  public static final int BOOLCONST = 35;
  public static final int PROG = 31;
  public static final int KEYWORD_IF = 36;
  public static final int DIFF = 8;
  public static final int KEYWORD_PRINT = 44;
  public static final int GR = 9;
}

